package com.example.webfluxdemo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "Tweet")
public class TweetTable {

    @DynamoDBAutoGeneratedKey
    private String id;
    private String text;
    private String createdAt;

//    public TweetTable(String text) {
//        this.text = text;
//        this.createdAt = LocalDateTime.now().toString();
//    }
//
//    public TweetTable(String id, String text, String createdAt) {
//        this.id = id;
//        this.text = text;
//        this.createdAt = createdAt;
//    }

    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBHashKey(attributeName = "Text")
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @DynamoDBRangeKey(attributeName = "CreatedAt")
    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
}
